ALTER TABLE "Download" ADD COLUMN "priority" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Download" ADD COLUMN "attempts" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Download" ADD COLUMN "nextRetryAt" DATETIME;
